### PR TITLE
Ability to grab URLs from clipboard

### PR DESCRIPTION
**Pull request by aliaksei135**
Added ability to grab URLs from the clipboard and paste them into the URL field. Clipboard is polled every second and field updated accordingly

### CODE REVIEW

**Comment by icecoldfire** [comment]
I would check an URL with a module like urlprase or an regular expression. 

What is wrong with just paste in the URL field? Isn't this unwanted behavior for some users?

**Comment by aliaksei135** [comment]
Usually when copying something to the clipboard with AudioJack already open (on a second monitor in my case) , 9 times out of 10 the clipboard content to destined for AudioJack, so why not skip the user having to select the field and paste in, when they could glance at the UI and see their URL already in there, then they would need to hit Go.

**Comment by icecoldfire** [comment]
I like the idea and I want to help. Maybe is it possible for adding an option to enabling and disabling this option? We can store this in an settings file. Is it possible to resolve the conflicts?

**Comment by aliaksei135** [comment]
Merged upstream and conflicts resolved! Hold off on the merge until I implement proper URL validation

**Comment by aliaksei135** [comment]
[validators](https://validators.readthedocs.io/en/latest/) used for URL validation now

**Comment by icecoldfire** [comment]
Nice but what is wrong with the default Python 2 library urlparse? You can use it like this: http://stackoverflow.com/questions/25259134/how-can-i-check-whether-a-url-is-valid-using-urlparse

**Review by Blue9 — APPROVED** [review]
Thanks for the contribution! Looks like a cool feature.

**Pull request merged**
